# Introduction To Numpy
* Numerical Python
* Linear Algebra for Python
* Has bindings to c Library
* High Performanace Scientific Computing

In [1]:
import numpy as np

 Numpy ndarray - A multidimensional Array Object


* HOMOGENOUES DATA -  means all the elements of numpy array are of same data type

In [3]:
lst_data = list(range(1,11))
print(lst_data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
np.array(lst_data) 
## creating here array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
e = np.array([lst_data])
## asigining the array in object e

In [19]:
print(e.shape)
print(e.ndim)
print(e)

(1, 10)
2
[[ 1  2  3  4  5  6  7  8  9 10]]


In [10]:
print(e.ndim)

2


In [14]:
np1 = np.array(lst_data)

In [15]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
print(type(np1))

<class 'numpy.ndarray'>


## Shape

In [17]:
np1.shape

(10,)

In [18]:
np1.ndim

1

## Create a multi-dimensinal array

In [20]:
my_matrix = [[1,2,3,10],[4,5,6,11],[7,8,9,12]]

In [23]:
md_arr = np.array(my_matrix)
## creating a matrix

In [24]:
md_arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [25]:
md_arr.shape

(3, 4)

In [26]:
md_arr.ndim

2

In [27]:
md_arr.dtype

dtype('int32')

In [28]:
## Exercise create a 3 dimensional array using list
# should be 2x3x4

In [40]:
my_matrix = [[[1,2,3,10],[4,5,6,11],[7,8,9,12]],[[11,12,13,100],[14,15,16,111],[17,18,19,112]]]

In [46]:
md_arr1 = np.array(my_matrix)
## creating a matrix

In [48]:
md_arr1.shape

(2, 3, 4)

In [49]:
md_arr1

array([[[  1,   2,   3,  10],
        [  4,   5,   6,  11],
        [  7,   8,   9,  12]],

       [[ 11,  12,  13, 100],
        [ 14,  15,  16, 111],
        [ 17,  18,  19, 112]]])

In [51]:
md_arr1.ndim

3

In [53]:
md_arr1.dtype
## native scaler datatype

dtype('int32')

In [54]:
arr1 = np.array([1,2,3,4,5], dtype = float)

In [55]:
arr1

array([1., 2., 3., 4., 5.])

In [56]:
arr1.dtype

dtype('float64')

In [58]:
lst_odd_size = [[1,2,3],[4,5],[7,8,9]]
lst_odd_size

[[1, 2, 3], [4, 5], [7, 8, 9]]

In [59]:
md_arr_odd = np.array(lst_odd_size)

<ipython-input-59-61f8ca2a3b97>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  md_arr_odd = np.array(lst_odd_size)


In [60]:
md_arr_odd

array([list([1, 2, 3]), list([4, 5]), list([7, 8, 9])], dtype=object)

In [63]:
md_arr_odd.shape
## here the sahpe is 3 as each element is stored as object and ndim should of 1 length

(3,)

In [64]:
md_arr_odd.ndim

1

In [65]:
my_list =[1,2,3,4,5,6]

In [66]:
arr1 = np.array(my_list, dtype ='i')
## we had provided datatype dtype = i so it will create using int32

In [67]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [68]:
arr1.shape

(6,)

In [71]:
arr2 = arr1.reshape(3,2)
# converting from 1 dimensional to 2 using resahpe  by assigning 3rows and 2 column

In [72]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [73]:
arr2.ndim

2

In [75]:
## Reshape to 3,-1
## So it will not take -1 as there is no -ve dimension so it will take only +ve values
arr3 = arr1.reshape(3,-1)

In [76]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [77]:
arr3.shape

(3, 2)

In [79]:
my_list1 = list(range(1,6))
my_list2 = list(range(10,15))
my_list3 = list(range(20,25))

In [80]:
my_list1,my_list2,my_list3

([1, 2, 3, 4, 5], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24])

In [82]:
mul_arr = np.array([my_list1, my_list2, my_list3])

In [83]:
mul_arr

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [84]:
mul_arr.shape

(3, 5)

In [86]:
mul_arr_15 = mul_arr.reshape(1,15)

In [87]:
mul_arr_15 .shape

(1, 15)

In [88]:
mul_arr_15 .ndim

2

In [89]:
mul_arr_51 = mul_arr_15 .reshape(15,1)

In [91]:
mul_arr_51.shape

(15, 1)

In [92]:
mul_arr_51.ndim

2

In [93]:
mul_arr_15 

array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24]])

In [94]:
mul_arr_51

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [10],
       [11],
       [12],
       [13],
       [14],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [95]:
#Conert this into 3x2x4 dimensional array
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [96]:
a.ndim

1

In [97]:
a1 = a.reshape(3,2,4)

In [98]:
a1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [99]:
a1.ndim

3

In [100]:
x = np.array([1,2,3], dtype = np.int8)

In [101]:
print(x.itemsize)
#  This will take 1 byts

1


In [102]:
x = np.array([1,2,3], dtype = np.int64)

In [103]:
print(x.itemsize)
# This will atke 8 byts

8


In [104]:
x = np.array([1,2,3], dtype = np.int32)

In [105]:
print(x.itemsize)
# This will take 4 byts

4


In [109]:
arr1 = np.arange(0, 11, 2) # 0 -Start Element, 11 is End element and 2 is Step Count

In [107]:
arr1

array([ 0,  2,  4,  6,  8, 10])

In [111]:
arr = np.random.randint(20,30,10)
## Generate a random number. So in np we have a random model from that we have randint. SO what it does is it generates a random numbers starting from 20 to 30 and hw many we wants that is 10 random numbers

In [112]:
arr

array([23, 29, 22, 21, 28, 22, 21, 27, 28, 27])

In [113]:
len(arr)

10

In [114]:
## Index -> Indexing always starts from 0
arr[0]

23

In [115]:
arr[5:8]

array([22, 21, 27])

In [118]:
arr[:3]

array([23, 29, 22])

In [119]:
arr[-1]

27

In [120]:
# Broadcasting
# Array slices are *actually* views on the original array
# That means, data isn't copied, and any modifications to view would be reflected back to the source array

In [122]:
arr

array([23, 29, 22, 21, 28, 22, 21, 27, 28, 27])

In [124]:
arr[0:5] = 99

In [125]:
arr

array([99, 99, 99, 99, 99, 22, 21, 27, 28, 27])

In [126]:
new_arr = np.random.randint(10, 20, 10)

In [127]:
new_arr

array([14, 12, 11, 13, 15, 12, 18, 18, 18, 14])

In [128]:
slice_new_arr = new_arr[0:5]

In [129]:
slice_new_arr

array([14, 12, 11, 13, 15])

In [130]:
slice_new_arr[0] = 100 

In [131]:
slice_new_arr

array([100,  12,  11,  13,  15])

In [132]:
## Now set all the elements to 111
slice_new_arr[:] = 111

In [133]:
slice_new_arr

array([111, 111, 111, 111, 111])

In [135]:
new_arr

array([111, 111, 111, 111, 111,  12,  18,  18,  18,  14])

In [136]:
new_arr_copy = new_arr.copy()

In [137]:
new_arr

array([111, 111, 111, 111, 111,  12,  18,  18,  18,  14])

In [139]:
new_arr_copy

array([111, 111, 111, 111, 111,  12,  18,  18,  18,  14])

In [140]:
new_arr_copy[0:5] = 123

In [141]:
new_arr_copy

array([123, 123, 123, 123, 123,  12,  18,  18,  18,  14])

In [142]:
new_arr

array([111, 111, 111, 111, 111,  12,  18,  18,  18,  14])

In [143]:
a = list(range(1,11))

In [144]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [145]:
b= a[0:5]

In [146]:
b

[1, 2, 3, 4, 5]

In [147]:
b[0] = 100

In [148]:
b

[100, 2, 3, 4, 5]

In [150]:
b[0:3] = 123
# this will not work here for this as this b is assigned by array

TypeError: can only assign an iterable

In [151]:
new_arr = np.random.randint(10,20,100)

In [152]:
new_arr

array([18, 16, 18, 15, 18, 10, 16, 18, 17, 14, 10, 13, 16, 12, 14, 11, 11,
       13, 14, 16, 13, 11, 16, 17, 19, 18, 16, 14, 18, 19, 16, 14, 13, 10,
       18, 12, 17, 14, 10, 14, 17, 17, 12, 16, 16, 19, 18, 15, 15, 11, 17,
       13, 12, 10, 17, 19, 16, 15, 16, 15, 17, 19, 19, 12, 17, 18, 17, 12,
       12, 14, 10, 10, 17, 15, 16, 11, 16, 13, 17, 10, 19, 10, 11, 14, 14,
       15, 11, 17, 17, 16, 14, 10, 19, 10, 18, 18, 11, 15, 16, 19])

In [154]:
x = np.array([[1,2],[3,4]], dtype = np.float64)

In [155]:
y = np.array([[5,6],[7,8]], dtype = np.float64)

In [156]:
x

array([[1., 2.],
       [3., 4.]])

In [157]:
y

array([[5., 6.],
       [7., 8.]])

In [158]:
x.ndim, y.ndim

(2, 2)

In [159]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [160]:
x - y

array([[-4., -4.],
       [-4., -4.]])

In [161]:
y - x

array([[4., 4.],
       [4., 4.]])

In [162]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [163]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [164]:
np.subtract(y,x)

array([[4., 4.],
       [4., 4.]])

In [165]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [166]:
# dot product

In [167]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [168]:
x,y

(array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]]))

In [169]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [170]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [171]:
x

array([[1., 2.],
       [3., 4.]])

In [172]:
# If we want to compute sum of all the elements 
print(np.sum(x)) ## Compute sum of all elements of the array

10.0


In [173]:
print(np.sum(x,axis = 0)) ## Compute sum of each column

[4. 6.]


In [174]:
print(np.sum(x,axis = 1)) ## Compute sum of each row

[3. 7.]


In [184]:
arr = np.arange(15)

In [185]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [187]:
arr = arr.reshape(3,5)

In [188]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [189]:
arr.T
## T is transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [190]:
np.max(arr)

14

In [191]:
np.min(arr)

0

In [192]:
x

array([[1., 2.],
       [3., 4.]])

In [193]:
y

array([[5., 6.],
       [7., 8.]])

In [194]:
np.maximum(x,y)

array([[5., 6.],
       [7., 8.]])

In [195]:
a = np.array([[1,2],[2,1]], dtype = np.float64)
b = np.array([[2,1],[1,2]], dtype = np.float64)

In [196]:
np.maximum(a, b)

array([[2., 2.],
       [2., 2.]])

In [197]:
np.minimum(a,b)

array([[1., 1.],
       [1., 1.]])

In [ ]:
## So if you want to construct zero array with same dimension

In [198]:
a

array([[1., 2.],
       [2., 1.]])

In [199]:
b

array([[2., 1.],
       [1., 2.]])

In [200]:
zeros_a = np.zeros_like(a)

In [201]:
zeros_a

array([[0., 0.],
       [0., 0.]])

In [ ]:
## So if you want to construct ones array with same dimension

In [203]:
ones_a = np.ones_like(a)

In [204]:
ones_a

array([[1., 1.],
       [1., 1.]])

In [207]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [208]:
a

array([[1., 2.],
       [2., 1.]])

In [209]:
i = 10

In [210]:
print('Cell 1')
print('Cell 2')
print('Cell 3')

Cell 1
Cell 2
Cell 3


In [213]:
ones_a
np.zeros((3,3))
a

array([[1., 2.],
       [2., 1.]])

In [216]:
a = np.array([[1,2],[2,1]], dtype = np.float64)
b = np.array([[2,1],[1,2]], dtype = np.float64)

np.maximum(a,b)
np.minimum(a,b)

a


b




array([[2., 1.],
       [1., 2.]])

In [217]:
a = np.arange(24)
print(a)
a.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


1

In [218]:
b = a.reshape(2,4,3)
b.ndim

3

In [219]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [220]:
b[0][1][0]

3

In [222]:
b[0][1][1]

4

In [221]:
b[1][1][0]

15

In [223]:
for x in range(0,2):
    for y in range(0, 4):
        for z in range(0,3):
            print(b[x][y][z])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [224]:
c = a.reshape(2,2,3,2)

In [225]:
c

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [226]:
c.ndim

4

# Series

In [227]:
import numpy as np
import pandas as pd

In [228]:
labels = ['a', 'b', 'c']
lst_data = [10, 20, 30]

In [230]:
s_lst_data = pd.Series(lst_data)

In [231]:
s_lst_data

0    10
1    20
2    30
dtype: int64

In [234]:
## So here the index is 0,1,2 and if we want to chamge the index to a,b,c than provide the labels object to index. See the code below

In [232]:
s_lst_data_label = pd.Series(lst_data, index = labels)

In [233]:
s_lst_data_label

a    10
b    20
c    30
dtype: int64

In [235]:
## So there is multiple data set and we want all of them will follow the same labels and index than that time it is very useful

In [236]:
s_lst_data_label.index

Index(['a', 'b', 'c'], dtype='object')

In [237]:
# Below we had an array
arr = np.array([11,22,33])

In [238]:
arr

array([11, 22, 33])

In [ ]:
# using this array we are creating a series and same set of labels

In [239]:
s_arr_labels = pd.Series(arr, labels)

In [ ]:
s_arr_labels


In [241]:
## Below we had a dict and we are creating a series from this dict

In [255]:
d = {'a': 41, 'b': 51, 'c': 61}

In [256]:
pd.Series(d)

a    41
b    51
c    61
dtype: int64

In [257]:
d= {'India': 'Delhi', 'Srilanka': 'Colombo', 'Australia': 'Sydeny'}

In [258]:
d

{'India': 'Delhi', 'Srilanka': 'Colombo', 'Australia': 'Sydeny'}

In [259]:
pd.Series(d)

India          Delhi
Srilanka     Colombo
Australia     Sydeny
dtype: object

In [260]:
pd.Series(d, labels)

a    NaN
b    NaN
a    NaN
dtype: object

In [261]:
labels = ['a', 'b', 'a']
lst_data = [10, 20, 30]

In [262]:
pd.Series(lst_data, labels)

a    10
b    20
a    30
dtype: int64

In [263]:
d= {'India': 'Delhi', 'Srilanka': 'Colombo', 'a': 'Sydeny'}

In [264]:
s1= pd.Series(d, labels)

In [265]:
s1

a    Sydeny
b       NaN
a    Sydeny
dtype: object

In [266]:
s1['a']

a    Sydeny
a    Sydeny
dtype: object

In [268]:
s_example = pd.Series([4,7,-5,3], index = ['d', 'b', 'a', 'c'])

In [269]:
s_example

d    4
b    7
a   -5
c    3
dtype: int64

In [270]:
s_example.values

array([ 4,  7, -5,  3], dtype=int64)

In [271]:
s_example.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [272]:
s_example['d']

4

In [273]:
s_example['d'] = 100

In [274]:
s_example

d    100
b      7
a     -5
c      3
dtype: int64

In [275]:
## Give me all the elements where value is greater than > 0

In [276]:
s_example > 0

d     True
b     True
a    False
c     True
dtype: bool

In [277]:
s_example[s_example>0]

d    100
b      7
c      3
dtype: int64

In [281]:
## in
## By Default it will check for the lables i.e index

In [282]:
'd' in s_example

True

In [283]:
100 in s_example

False

In [284]:
100. in s_example.values

True

In [285]:
 s_example.values

array([100,   7,  -5,   3], dtype=int64)